### ISSUE TITLE
Free energy calculation step not finding files from equilibration step

### ISSUE THREAD

**Issue by mixarcid** [GHeinzelmann/BAT.py#32]
I'm trying to run the example calculation (I haven't changed input-dd.in). The equilibration step `python BAT.py -i input-dd.in -s equil` appeared to run successfully -- I've attached the full output below.

[equil.txt](https://github.com/GHeinzelmann/BAT.py/files/13365547/equil.txt)

However, when I run the free energy step `python BAT.py -i input-dd.in -s fe`, I get the following error:
```
lambda values: [0.025446043828620757, 0.12923440720030277, 0.2970774243113014, 0.5, 0.7029225756886985, 0.8707655927996972, 0.9745539561713792]
Gaussian weights: [0.06474248308443532, 0.1398526957446383, 0.19091502525255916, 0.20897959183673448, 0.19091502525255916, 0.1398526957446383, 0.06474248308443532]
Setting up pose0
window: c00 weight: 0.0
Traceback (most recent call last):
  File "[...]/BAT/BAT.py", line 720, in <module>
    anch = build.build_dec(fwin, hmr, mol, pose, comp, win, water_model, ntpr, ntwr, ntwe, ntwx, cut, gamma_ln, barostat, receptor_ff, ligand_ff, dt, sdr_dist, dec_method, l1_x, l1_y, l1_z, l1_range, min_adis, max_adis, ion_def, other_mol, solv_shell)
  File "/home/boris/Repos/BAT.py/BAT/lib/build.py", line 440, in build_dec
    shutil.copy('../../../equil/'+pose+'/md%02d.rst7' %fwin, './')
  File "[...]/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "[...]/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../../../equil/pose0/md08.rst7'
```
Any idea what's going on here? Thanks for your help!

**Comment by mixarcid** [comment]
Nvm -- I see this is a duplicate of https://github.com/GHeinzelmann/BAT.py/issues/24
